version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: examshield-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: examshield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: examshield-cache
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
